version: '3.8'

services:
  db:
    image: postgres:14
    container_name: rag-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: talgat
      POSTGRES_PASSWORD: talgat_admin
      POSTGRES_DB: ragdb
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: rag-backend
    depends_on:
      - db
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./embeddings:/app/embeddings
      - ./data:/app/data
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build: ./frontend
    container_name: rag-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: npm run dev

volumes:
  pg_data:
